ProjectTracker/ProjectTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('guide/', include('guide.urls')),
    path('student/',include('student.urls')),
    path('project/',include('project.urls')),
    path('team/',include('team.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectTracker/home/urls.py
from django.urls import path
from .import views

app_name = "home"

urlpatterns = [
    path('', views.home, name="home"),
    path('support/', views.support, name="support"),
]

ProjectTracker/project/urls.py
from django.urls import path
from .import views

app_name = "project"

urlpatterns = [
    path('', views.project_list, name="project_list"),
    path('add_project/', views.add_project, name="add_project"),
    path('update_project/<int:pk>/', views.update_project, name="update_project"),
    path('delete_project/<int:pk>/', views.delete_project, name="delete_project"),

]

ProjectTracker/project/models.py
from django.db import models
from guide.models import Guide
from team.models import Team

# Create your models here.


class Project(models.Model):
    project_title = models.CharField(max_length=300)
    project_desc = models.TextField(max_length=1000)
    project_guide = models.ForeignKey(Guide, on_delete=models.CASCADE)
    team_name = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.team_name}--{self.project_title}'

ProjectTracker/project/forms.py
from django import forms
from .models import Project


class ProjectRegistration(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        labels = {
            'project_title': 'Project Title',
            'project_desc': 'Project Description',
            'project_guide': 'Project Guide',
            'team_name': 'Team Name',

        }
        widgets = {
            'project_title': forms.TextInput(attrs={'class': 'form-control'}),
            'project_desc': forms.TextInput(attrs={'class': 'form-control'}),
            'project_guide': forms.Select(attrs={'class': 'form-control'}),
            'team_name': forms.Select(attrs={'class': 'form-control'}),
        }

ProjectTracker/project/views.py
from django.shortcuts import render, redirect
from .models import Project
from .forms import ProjectRegistration

# Create your views here.


def project_list(request):
    projects = Project.objects.all()
    context = {'projects': projects}
    return render(request, 'project/project.html', context)


def add_project(request):
    if request.method == 'POST':
        form = ProjectRegistration(request.POST)
        if form.is_valid():
            form.save()
        return redirect('project:project_list')
    else:
        form = ProjectRegistration()
    context = {'form': form}
    return render(request, "project/add_project.html", context)


def update_project(request, pk):
    project = Project.objects.get(id=pk)
    if request.method == 'POST':
        form = ProjectRegistration(request.POST, instance=project)
        if form.is_valid():
            form.save()
        return redirect('project:project_list')
    else:
        form = ProjectRegistration(instance=project)
    context = {'form': form}
    return render(request, "project/update_project.html", context)


def delete_project(request, pk):
    project = Project.objects.get(id=pk)
    project.delete()
    return redirect('project:project_list')

ProjectTracker/project/templates/project/add_project.html
{% extends 'home/base.html' %}

{% load static %}


{% block title %}
Add Project
{% endblock title %}


{% block content %}
<div class="container mt-3">
    <div class="row card card-body rounded"
        style="justify-content: center; align-items: center; width: 75%;margin: auto; padding: 20px;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Add Project</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

ProjectTracker/project/templates/project/project.html
{% extends 'home/base.html' %}

{% load static %}



{% block title %}
Project Details
{% endblock title %}




{% block content %}
<div class="container">
    <div class="row m-2">
        <div class="col-md">

            <a href="{% url 'project:add_project' %}" class="btn btn-primary">Add Project</a>
        </div>

    </div>
    <div class="row m-2">
        <div class="col-md">
            <h3 class="alert alert-success text-center">Project List</h3>
            <div class="card card-body table-responsive">

                <table class="table">
                    <thead>
                        <tr>
                            <th>Sr.No</th>
                            <th>Project Title</th>
                            <th>Project Guide</th>
                            <th>Team Name </th>
                            <th>Action </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}



                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{project.project_title}}</td>
                            <td>{{project.project_guide}}</td>
                            <td>{{project.team_name}} </td>
                            <td>
                                <a href="{% url 'project:update_project' project.id %}" class="edit me-2" title="Edit"
                                    data-toggle="tooltip"><i class="bi bi-pencil-fill"></i></a>
                                <a href="{% url 'project:delete_project' project.id %}" class="delete text-danger" title="Delete" data-toggle="tooltip"><i
                                        class="bi bi-trash3-fill"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ProjectTracker/project/templates/project/update_project.html
{% extends 'home/base.html' %}

{% load static %}


{% block title %}
Update Project
{% endblock title %}


{% block content %}
<div class="container mt-3">
    <div class="row card card-body rounded"
        style="justify-content: center; align-items: center; width: 75%;margin: auto; padding: 20px;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Update Project</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}