ProjectTracker/ProjectTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('guide/', include('guide.urls')),
    path('student/',include('student.urls')),
    path('project/',include('project.urls')),
    path('team/',include('team.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectTracker/guide/urls.py
from django.urls import path
from .import views

app_name = "guide"

urlpatterns = [
    path('', views.guide_list, name="guide_list"),
    path('add_guide/', views.add_guide, name="add_guide"),
    path('update_guide/<int:pk>/', views.update_guide, name="update_guide"),
    path('delete_guide/<int:pk>/', views.delete_guide, name="delete_guide"),

]

ProjectTracker/home/urls.py
from django.urls import path
from .import views

app_name = "home"

urlpatterns = [
    path('', views.home, name="home"),
    path('support/', views.support, name="support"),
]

ProjectTracker/guide/models.py
from django.db import models

# Create your models here.

SPECIALIZATION = (
    ("AI/ML", "AI/ML"),
    ("Cloud", "Cloud"),
    ("Blockchain", "Blockchain"),
    ("Cyber Security", "Cyber Security"),
    ("HCI", "HCI"),
    ("Robotics", "Robotics"),
)

DEPARTMENT = (
    ("CS", "CS"),
    ("IT", "IT"),
    ("ENTC", "ENTC"),
    ("MECH", "MECH"),
)


class Guide(models.Model):
    guide_name = models.CharField(max_length=200)
    guide_department = models.CharField(
        max_length=200, choices=DEPARTMENT)
    guide_email = models.EmailField()
    guide_mobile = models.CharField(max_length=20)
    guide_specilization = models.CharField(
        max_length=50, choices=SPECIALIZATION)

    def __str__(self):
        return self.guide_name

ProjectTracker/guide/forms.py
from django import forms
from .models import Guide


class GuideRegistration(forms.ModelForm):
    class Meta:
        model = Guide
        fields = '__all__'
        labels = {
            'guide_name': 'Guide Name',
            'guide_department': 'Department',
            'guide_email': 'Email',
            'guide_mobile': 'Contact',
            'guide_specilization': 'Specilization',

        }
        widgets = {
            'guide_name': forms.TextInput(attrs={'class': 'form-control'}),
            'guide_department': forms.Select(attrs={'class': 'form-control'}),
            'guide_email': forms.EmailInput(attrs={'class': 'form-control'}),
            'guide_mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'guide_specilization': forms.Select(attrs={'class': 'form-control'}),
        }

ProjectTracker/guide/views.py
from django.shortcuts import render, redirect
from .models import Guide
from .forms import GuideRegistration
# Create your views here.


def guide_list(request):
    guides = Guide.objects.all()
    context = {'guides': guides}
    return render(request, "guide/guide.html", context)


def add_guide(request):
    if request.method == 'POST':
        form = GuideRegistration(request.POST)
        if form.is_valid():
            form.save()
        return redirect('guide:guide_list')
    else:
        form = GuideRegistration()
    context = {'form': form}
    return render(request, "guide/add_guide.html", context)


def update_guide(request, pk):
    guide = Guide.objects.get(id=pk)
    if request.method == 'POST':
        form = GuideRegistration(request.POST, instance=guide)
        if form.is_valid():
            form.save()
        return redirect('guide:guide_list')
    else:
        form = GuideRegistration(instance=guide)
    context = {'form': form}
    return render(request, "guide/update_guide.html", context)


def delete_guide(request, pk):
    guide = Guide.objects.get(id=pk)
    guide.delete()
    return redirect('guide:guide_list')
   

ProjectTracker/guide/templates/guide/add_guide.html
{% extends 'home/base.html' %}

{% load static %}


{% block title %}
Add Guide
{% endblock title %}


{% block content %}
<div class="container mt-3">
    <div class="row card card-body rounded"
        style="justify-content: center; align-items: center; width: 75%;margin: auto; padding: 20px;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Add Guide</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

ProjectTracker/guide/templates/guide/guide.html
{% extends 'home/base.html' %}

{% load static %}



{% block title %}
Guide Details
{% endblock title %}




{% block content %}
<div class="container">
    <div class="row m-2">
        <div class="col-md">

            <a href="{% url 'guide:add_guide' %}" class="btn btn-primary">Add Guide</a>
        </div>

    </div>
    <div class="row m-2">
        <div class="col-md">
            <h3 class="alert alert-success text-center">Guide List</h3>
            <div class="card card-body table-responsive">

                <table class="table">
                    <thead>
                        <tr>
                            <th>Sr.No</th>
                            <th>Guide Name</th>
                            <th>Department</th>
                            <th>Specialization </th>
                            <th>Action </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for guide in guides %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>Prof. {{guide.guide_name}}</td>
                            <td>{{guide.guide_department}}</td>
                            <td>{{guide.guide_specilization}} </td>
                            <td>
                                <a href="{% url 'guide:update_guide' guide.id %}" class="edit me-2" title="Edit"
                                    data-toggle="tooltip"><i class="bi bi-pencil-fill"></i></a>
                                <a href="{% url 'guide:delete_guide' guide.id %}" class="delete text-danger"
                                    title="Delete" data-toggle="tooltip"><i class="bi bi-trash3-fill"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ProjectTracker/guide/templates/guide/update_guide.html
{% extends 'home/base.html' %}

{% load static %}


{% block title %}
Update Guide
{% endblock title %}


{% block content %}
<div class="container mt-3">
    <div class="row card card-body rounded"
        style="justify-content: center; align-items: center; width: 75%;margin: auto; padding: 20px;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Update Guide</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}