ProjectTracker/ProjectTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('guide/', include('guide.urls')),
    path('student/',include('student.urls')),
    path('project/',include('project.urls')),
    path('team/',include('team.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectTracker/home/urls.py
from django.urls import path
from .import views

app_name = "home"

urlpatterns = [
    path('', views.home, name="home"),
    path('support/', views.support, name="support"),
]

ProjectTracker/student/urls.py
from django.urls import path
from .import views

app_name = "student"

urlpatterns = [
    path('', views.student_list, name="student_list"),
    path('add_student/', views.add_student, name="add_student"),
    path('update_student/<int:pk>/', views.update_student, name="update_student"),
    path('delete_student/<int:pk>/', views.delete_student, name="delete_student"),

]

ProjectTracker/student/models.py
from unicodedata import name
from django.db import models

# Create your models here.

DIV = (
    ("A", "A"),
    ("B", "B"),
    ("C", "C"),
    ("D", "D"),
)

DEPARTMENT = (
    ("CS", "CS"),
    ("IT", "IT"),
    ("ENTC", "ENTC"),
    ("MECH", "MECH"),
)


class Student(models.Model):
    gr_no = models.CharField(max_length=20)
    student_name = models.CharField(max_length=200)
    student_div = models.CharField(max_length=10, choices=DIV)
    student_branch = models.CharField(max_length=200, choices=DEPARTMENT)
    student_roll = models.CharField(max_length=10)
    student_email = models.EmailField()
    student_mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.student_name

ProjectTracker/student/forms.py
from django import forms
from .models import Student


class StudentRegistration(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        labels = {
            'gr_no': 'Registration No',
            'student_name': 'Name',
            'student_div': 'Division',
            'student_branch': 'Branch',
            'student_roll': 'Roll No',
            'student_email': 'Email',
            'student_mobile': 'Contact',

        }
        widgets = {
            'gr_no': forms.TextInput(attrs={'class': 'form-control'}),
            'student_name': forms.TextInput(attrs={'class': 'form-control'}),
            'student_div': forms.Select(attrs={'class': 'form-control'}),
            'student_branch': forms.Select(attrs={'class': 'form-control'}),
            'student_roll': forms.TextInput(attrs={'class': 'form-control'}),
            'student_email': forms.EmailInput(attrs={'class': 'form-control'}),
            'student_mobile': forms.TextInput(attrs={'class': 'form-control'}),
        }

ProjectTracker/student/views.py
from django.shortcuts import render,redirect
from .models import Student
from .forms import StudentRegistration
# Create your views here.


def student_list(request):
    students = Student.objects.all()
    context = {'students': students}
    return render(request, "student/student.html", context)


def add_student(request):
    if request.method == 'POST':
        form = StudentRegistration(request.POST)
        if form.is_valid():
            form.save()
        return redirect('student:student')
    else:
        form = StudentRegistration()
    context = {'form': form}
    return render(request, "student/add_student.html", context)



def update_student(request, pk):
    student = Student.objects.get(id=pk)
    if request.method == 'POST':
        form = StudentRegistration(request.POST, instance=student)
        if form.is_valid():
            form.save()
        return redirect('student:student_list')
    else:
        form = StudentRegistration(instance=student)
    context = {'form': form}
    return render(request, "student/update_student.html", context)



def delete_student(request, pk):
    student = Student.objects.get(id=pk)
    student.delete()
    return redirect('student:student_list')

ProjectTracker/student/templates/student/add_student.html
{% extends 'home/base.html' %}

{% load static %}


{% block title %}
Add Student
{% endblock title %}


{% block content %}
<div class="container mt-3">
    <div class="row card card-body rounded"
        style="justify-content: center; align-items: center; width: 75%;margin: auto; padding: 20px;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Add new student</h4>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

ProjectTracker/student/templates/student/student.html
{% extends 'home/base.html' %}

{% load static %}



{% block title %}
Student Details
{% endblock title %}




{% block content %}
<div class="container">
    <div class="row m-2">
        <div class="col-md">

            <a href="{% url 'student:add_student' %}" class="btn btn-primary">Add Student</a>
        </div>

    </div>

    <div class="row m-2">
        <div class="col-md">
            <h3 class="alert alert-success text-center">Student List</h3>
            <div class="card card-body table-responsive">

                <table class="table">
                    <thead>
                        <tr>
                            <th>Sr.No</th>
                            <th>Student Name</th>
                            <th>Department</th>
                            <th>Roll no </th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for student in students %}



                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{student.student_name}}</td>
                            <td>{{student.student_branch}}</td>
                            <td>{{student.student_roll}} </td>
                            <td>
                                <a href="{% url 'student:update_student' student.id %}" class="edit me-2" title="Edit"
                                    data-toggle="tooltip"><i class="bi bi-pencil-fill"></i></a>
                                <a href="{% url 'student:delete_student' student.id %}" class="delete text-danger" title="Delete" data-toggle="tooltip"><i
                                        class="bi bi-trash3-fill"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ProjectTracker/student/templates/student/update_student.html
{% extends 'home/base.html' %}

{% load static %}


{% block title %}
Update Student
{% endblock title %}


{% block content %}
<div class="container mt-3">
    <div class="row card card-body rounded"
        style="justify-content: center; align-items: center; width: 75%;margin: auto; padding: 20px;">
        <div class="col-md-8">
            <h4 class="text-center alert alert-info">Update Student</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Add">
            </form>
        </div>
    </div>
</div>
{% endblock content %}